//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDrape.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CinemaDrape.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CinemaDrapeQuickStartFocusAreaV3 {
            get {
                object obj = ResourceManager.GetObject("CinemaDrapeQuickStartFocusAreaV3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinemadrape.cinemadrape.
        /// </summary>
        internal static string StringDefaultSettingsFile {
            get {
                return ResourceManager.GetString("StringDefaultSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the Web page located at:.
        /// </summary>
        internal static string StringErrorLoadingUrl {
            get {
                return ResourceManager.GetString("StringErrorLoadingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click or tap anywhere inside the area underneath the drape that you want to autodetect. To cancel, press Escape, right-click or long tap..
        /// </summary>
        internal static string StringMenuAutodetectAreaStart {
            get {
                return ResourceManager.GetString("StringMenuAutodetectAreaStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click or tap anywhere inside the window underneath the drape that you want to autodetect. To cancel, press Escape, right-click or long tap..
        /// </summary>
        internal static string StringMenuAutodetectWindowStart {
            get {
                return ResourceManager.GetString("StringMenuAutodetectWindowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Opacity ({0:0%}).
        /// </summary>
        internal static string StringMenuOpacity {
            get {
                return ResourceManager.GetString("StringMenuOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide (&amp;Pause).
        /// </summary>
        internal static string StringMenuPause {
            get {
                return ResourceManager.GetString("StringMenuPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore.
        /// </summary>
        internal static string StringMenuRestore {
            get {
                return ResourceManager.GetString("StringMenuRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To restore CinemaDrape, left-click its icon. Or right-click to get the menu..
        /// </summary>
        internal static string StringPauseBalloonTip {
            get {
                return ResourceManager.GetString("StringPauseBalloonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pause and hide the drape to the taskbar notification area, double-click or press {0}..
        /// </summary>
        internal static string StringQuickPause {
            get {
                return ResourceManager.GetString("StringQuickPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoRestoreAreas.
        /// </summary>
        internal static string StringSettingsAutoRestoreAreas {
            get {
                return ResourceManager.GetString("StringSettingsAutoRestoreAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrapeColor.
        /// </summary>
        internal static string StringSettingsDrapeColor {
            get {
                return ResourceManager.GetString("StringSettingsDrapeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrapeOpacity.
        /// </summary>
        internal static string StringSettingsDrapeOpacity {
            get {
                return ResourceManager.GetString("StringSettingsDrapeOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FocusArea.
        /// </summary>
        internal static string StringSettingsFocusArea {
            get {
                return ResourceManager.GetString("StringSettingsFocusArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peek through opacity: {0}%.
        /// </summary>
        internal static string StringSettingsFormPeekOpacity {
            get {
                return ResourceManager.GetString("StringSettingsFormPeekOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        internal static string StringSettingsHotkey {
            get {
                return ResourceManager.GetString("StringSettingsHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeekOpacity.
        /// </summary>
        internal static string StringSettingsPeekOpacity {
            get {
                return ResourceManager.GetString("StringSettingsPeekOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickStartLocation.
        /// </summary>
        internal static string StringSettingsQuickStartLocation {
            get {
                return ResourceManager.GetString("StringSettingsQuickStartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowQuickStart.
        /// </summary>
        internal static string StringSettingsShowQuickStart {
            get {
                return ResourceManager.GetString("StringSettingsShowQuickStart", resourceCulture);
            }
        }
    }
}
